config/routes.rb
Rails.application.routes.draw do
  # root to: 'homes#top'
  # get "/about" => "homes#about"

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    # get 'top' => 'homes#top', as: 'top'
    root "homes#top"
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :members, only: [:index, :show, :edit, :update] do
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :wines, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "spots/spots_list" => "spots#spots_list"
    resources :spots, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "members/unsubscribe" => "members#unsubscribe", as: "confirm_unsubscribe"
    patch "members/withdraw" => "members#withdraw", as: "withdraw_members"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      # member doを使うと、ユーザーidが含まれてるurlを使えるようになる。
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :wines, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      # 1人のメンバーは1つの投稿に対して1回しかいいねできないためいいねのidはURLに含める必要がない(params[:id]を使わなくても良い)
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :spots, only: [:index, :show, :create, :new, :edit, :update]
  end

  # ゲストログイン用
  devise_scope :member do
    post "members/guest_sign_in", to: "members/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :wine
  
  validates :comment, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    Comment.find(params[:id]).destroy
    @comment = Comment.new
    @wine = Wine.find(params[:wine_id])
  end

  private
    def comment_params
      params.require(:comment).permit(:wine_id, :member_id, :comment)
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/_comment.html.erb
<div class="comment_contents">
  <% wine.comments.each do |comment| %>

        <table class="table comment_table">
          <tr>
            <td class="d-flex" style="width: 20%">
              <%= image_tag comment.member.get_profile_image(40,40), class: "rounded-circle comment_image" %>&ensp;
              <%= link_to wines_myindex_path(wine.member.id), remote: true do %>
                <%= comment.member.name %>
              <% end %>
            </td>
            <td style="width: 20%"><%= comment.created_at.strftime('%Y/%m/%d') %></td>
            <td style="width: 40%"><%= comment.comment %></td>
            <td style="width: 20%">
                <%= link_to "Delete", admin_wine_comment_path(comment.wine, comment), remote: true, method: :delete %>
            </td>
          </tr>
        </table>

  <% end %>
</div>

app/views/admin/comments/_counter.html.erb
<i class="far fa-comment"></i><%= wine.comments.count %>

app/views/admin/comments/destroy.js.erb
$(".comment").html("<%= j(render 'admin/comments/comment', wine: @wine) %>");
$(".comments_count").html("<%= j(render 'admin/comments/counter', wine: @wine) %>");