config/routes.rb
Rails.application.routes.draw do
  # root to: 'homes#top'
  # get "/about" => "homes#about"

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    # get 'top' => 'homes#top', as: 'top'
    root "homes#top"
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :members, only: [:index, :show, :edit, :update] do
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :wines, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "spots/spots_list" => "spots#spots_list"
    resources :spots, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "members/unsubscribe" => "members#unsubscribe", as: "confirm_unsubscribe"
    patch "members/withdraw" => "members#withdraw", as: "withdraw_members"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      # member doを使うと、ユーザーidが含まれてるurlを使えるようになる。
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :wines, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      # 1人のメンバーは1つの投稿に対して1回しかいいねできないためいいねのidはURLに含める必要がない(params[:id]を使わなくても良い)
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :spots, only: [:index, :show, :create, :new, :edit, :update]
  end

  # ゲストログイン用
  devise_scope :member do
    post "members/guest_sign_in", to: "members/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }
  #  備考：パスワードデフォルトで６文字以上を要求している
  #  備考：メールアドレスはデフォルトで一意であることを要求している

  has_many :wines, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  
  # A：自分がフォローしているユーザーとの関連(与フォロー)
  # フォローする場合の中間テーブルを「relationships」と名付ける。外部キー「follower_id =フォローするユーザのid」で参照するカラムを指定
  # フォローする側(follower_id)を元にフォローされる側(followed_id)を引っ張ってくるので、primary_key(外部キー)をfollower_idに指定する必要がある
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人. followings = フォローしている人 (一覧画面で使う)
  # 自分がフォローした人を集めるには、"followed"モデルを参照することになるため、source: :followedを記述する。
  has_many :followings, through: :relationships, source: :followed

  # B：自分をフォローしているユーザーとの関連(被フォロー)
  # フォローされる場合の中間テーブルを「reverse_of_relationships」と名付ける。外部キー「followed_id =フォローされるユーザのid」で参照するカラムを指定
  # フォローされる側(followed_id)を元にフォローする側(follower_id)を引っ張ってくるので、primary_key(外部キー)をfollowed_idに指定する必要がある
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人  followers = フォローしてくれている人 (一覧画面で使う)
  # 自分のことをフォローした人を集めるには、"follower"モデルを参照することになるため、source: :followerを記述する。
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  # フォローをした時の処理(relationshipsコントローラで使用)
  # followed_id=フォローされるユーザのid
  def follow(member)
    relationships.create(followed_id: member.id)
  end
  # フォローを外す時の処理(relationshipsコントローラで使用)
  def unfollow(member)
    relationships.find_by(followed_id: member.id).destroy
  end
  # フォローしているか判定(viewで使用)
  def following?(member)
    followings.include?(member)
  end


  # プロフィール写真を表示するためのメソッドを作成
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  # ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないよう制約
  # is_deletedがfalseならtrueを返すようにしている。
  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ransack使用する際、出てきたエラーに下記文を記載するよう指示文があったので記述。
  def self.ransackable_attributes(auth_object = nil)
    ["email", "encrypted_password", "favorite_genre", "id", "introduction", "is_deleted", "name", "prefecture", "activated_true"]
  end

  # ゲストログイン用。app/controllers/members/sessions_controller.rbで記述したMember.guestのguestメソッドを定義
  def self.guest
    find_or_create_by!(name: "guestuser", email: "guest@example.com") do |member|
      member.password = SecureRandom.urlsafe_base64
      member.name = "guestuser"
      member.prefecture = 13
      member.favorite_genre = 2
      member.introduction = "ゲストユーザーです。"
    end
  end

  enum favorite_genre: {
    All: 0,
     Sparkling: 1, White: 2, Red: 3, Rose: 4, Orange: 5, Others: 6
   }

  enum prefecture: {
     "---": 0,
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
     沖縄県: 47
   }
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  def index
    @members = Member.all
    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = @members.ransack(search_params, activated_true: true)
      @title = "検索結果"
    else
      @q = @members.ransack(activated_true: true)
      @title = "全てのユーザー"
    end
    @members = @q.result.page(params[:page]).per(6)
  end

  def followings
    @member = Member.find(params[:id])
    @members = @member.followings
    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = @members.ransack(search_params, activated_true: true)
      @title = "検索結果(フォローしているユーザー)"
    else
      @q = @members.ransack(activated_true: true)
      @title = "フォローしているユーザー"
    end
    @members = @q.result.page(params[:page]).per(6)
  end

  def followers
    @member = Member.find(params[:id])
    @members = @member.followers
    if params[:q] && params[:q].reject { |key, value| value.blank? }.present?
      @q = @members.ransack(search_params, activated_true: true)
      @title = "検索結果(フォロワー)"
    else
      @q = @members.ransack(activated_true: true)
      @title = "フォロワー"
    end
    @members = @q.result.page(params[:page]).per(6)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "会員情報の更新が完了しました。"
      redirect_to admin_member_path(@member.id)
    else
      flash[:error] = "情報が足りていないか、または情報が正しくありません。"
      render :edit
    end
  end

  # ブックマークした投稿一覧
  def bookmarks
    @member = Member.find(params[:id])
    # ユーザーidが、このユーザーの、ブックマークのレコードを全て取得。そのwine_idも一緒に持ってくる
    # bookmarksには、あるユーザーがブックマークした投稿のidが入っている
    bookmarks = Bookmark.where(member_id: @member.id).pluck(:wine_id)
    @bookmark_wines = Wine.find(bookmarks)
    @genres = Genre.all
  end

  # フォローした人の投稿一覧
  def followings_wine
    @member = Member.find(params[:id])
    @members = @member.followings.where(is_deleted: false)
    @followings_wines = Wine.where(member_id: @members).order(id: "DESC")
    @genres = Genre.all
  end


  private
    def member_params
      params.require(:member).permit(:name, :email, :profile_image, :favorite_genre, :prefecture, :introduction, :is_deleted)
    end

    def search_params
      params.require(:q).permit(:name_cont)
    end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  def guest_sign_in
    member = Member.guest
    sign_in member
    redirect_to wines_myindex_path(member), notice: "guestuserでログインしました。"
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/_index.html.erb
<div class="container my-4">

  <div class="row">
    <div class="col text-center">
      <% provide(:title,'ユーザー検索') %>
      <h4><%= title %></h4>
    </div>
  </div>

  <div class="row member_index_search">
    <div class="col-sm-md">
      <%= render 'search_form', q: q, url: url %>
    </div>
  </div>

  <div class="row my-4 text-center">
    <div class="col-sm-md">

      <% unless members.empty? %>

      <table class="table member_index_table">
        <thead>
          <th>ユーザー名</th>
          <th class="sm_size">在住県</th>
          <th class="sm_size">好きなワインのジャンル</th>
          <th class="sm_size">ナチュール記録数</th>
          <th class="sm_size">フォロー数</th>
          <th class="sm_size">フォロワー数</th>
          <th>ステータス</th>
        </thead>
        <% members.each do |member| %>
        <tbody>
          <tr class="member_index_tbody_tr" data-href="../../../admin/wines/myindex/<%= member.id%>">
            <td>
              <%= image_tag member.get_profile_image(60,60), class: "rounded-circle" %>
              <%= member.name %>
            </td>
            <td class="sm_size"><%= member.prefecture %></td>
            <td class="sm_size"><%= member.favorite_genre %></td>
            <td class="sm_size"><%= member.wines.count %></td>
            <td class="sm_size"><%= member.followings.where(is_deleted: false).count %></td>
            <td class="sm_size"><%= member.followers.where(is_deleted: false).count %></td>
　　　　　　<% if member.is_deleted == false %>
              <td class="text-success">有効</td>
            <% else %>
              <td class="text-secondary">退会</td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>

      <% else %>
      <p>
      ユーザーが見つかりませんでした。<br>
      お探しのユーザー名を確認してください。
      </p>
      <% end %>

    </div>
  </div>
  
  <div class="d-flex justify-content-center">
    <%= paginate members, theme: 'bootstrap-5' %>
  </div>
      
</div>

<script>
  window.onload = function() { //HTMLを読み込んでからscriptを読み込む
    $(".member_index_tbody_tr").on('click', function() {
      window.location = $(this).data("href");
    });
  }
</script>

app/views/admin/members/_search_form.html.erb
<%= search_form_for(q, url: url) do |f| %>
  <h6>※ユーザー検索</h6>
<div class = "input-group">
  <%= f.text_field :name_cont, placeholder: "ユーザー名を入力" %>
  <%= f.submit '検索' %>
</div
<% end %>

app/views/admin/members/bookmarks.html.erb
<div class='container my-4 wine_index_container'>

  <%= render 'admin/wines/member_info', member: @member %>

  <div class="row">
    <h5 class="col-sm-md text-center mx-auto text_blue">
      <%= @member.name %>がブックマークした投稿🍷<!--<span> (<%#= @bookmark_wines.count %>件)</span> %> -->
    </h5>
  </div>
  
  <%#= render 'admin/wines/index', wines: @bookmark_wines, member: @member, genres: @genres %>
  
  <!-- タブ作成-->
<div class ="row justify-content-center mt-3" >
  <div class ="col">
    <ul id="tab-menu">
        <li><a href="#tab-All" class="active">All</a></li>
      <% @genres.each do |genre| %>
        <li><a href="#tab-<%= genre.genre_name %>" class=""><%= genre.genre_name %></a></li>
      <% end %>
      </ul>
   </div>
</div>

  <!-- タブの内容作成-->
  <div class ="row">
    <div id="tab-contents">
  
      <!-- Allを表示-->
      <div id="tab-All" class="tab">
        <% @bookmark_wines.each do |wine| %>
         <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
          <div id="bookmark_list_<%= wine.id %>">
            <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
              <div class ="card">
  
                <div class ="card_spot_name ml-2">
                  <%= link_to admin_spot_path(wine.spot) do %>
                    📍<%= wine.spot.spot_name %>
                  <% end %>
                </div>
                <div class ="card_wine_image text-center">
                  <%= link_to admin_wine_path(wine) do %>
                    <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                  <% end %>
                </div>
                <div class ="card_member_name ml-4 mt-1">
                 <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                    <%= wine.member.name %>
                  <% end %>
                </div>
                <div id= "wine_<%= wine.id %>">
                  <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                    <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                    <div class ="card_comment ml-5">
                      <%= link_to admin_wine_path(wine.id) do%>
                        <i class="far fa-comment"></i><%= wine.comments.count %>
                      <% end %>
                    </div>
                    <div class ="card_favorites favorite-btn mx-3">
                       ♡<%= wine.favorites.count %>
                    </div>
                  </div>
                </div>
  
              </div>
            </div>
          </div>
        <% end %>
      </div>
  
     <!-- ジャンルごとに表示-->
      <% @genres.each do |genre| %>
        <div id="tab-<%= genre.genre_name %>" class="tab">
          <%# ブックマークした一覧 %>
           <%#.wineに関連するブックマークテーブルをまとめて取得(include)し、bookmarksの中でmember_idを指定 %>
          <% genre.wines.includes(:bookmarks).where(bookmarks: {member_id: @member.id}).each do |wine| %>
            <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
            <div id="bookmark_list_<%= wine.id %>">
              <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
                <div class ="card">
  
                  <div class ="card_spot_name ml-2">
                    <%= link_to admin_spot_path(wine.spot) do %>
                     📍<%= wine.spot.spot_name %>
                    <% end %>
                  </div>
                  <div class ="card_wine_image text-center">
                    <%= link_to admin_wine_path(wine) do %>
                      <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                    <% end %>
                  </div>
                  <div class ="card_member_name ml-4 mt-1">
                    <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                      <%= wine.member.name %>
                    <% end %>
                  </div>
  
                  <div id= "wine_<%= wine.id %>">
                    <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                      <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                      <div class ="card_comment ml-5">
                        <%= link_to admin_wine_path(wine.id) do%>
                          <i class="far fa-comment"></i><%= wine.comments.count %>
                        <% end %>
                      </div>
                      <div class ="card_favorites favorite-btn mx-3">
                        ♡<%= wine.favorites.count %>
                      </div>
                    </div>
                  </div>
  
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  
    </div>
  </div>

</div>

app/views/admin/members/edit.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-sm-md-7">
      <h2><%= @member.name %>のユーザー登録情報編集</h2>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-md-7">
      <h6 class="text_red">※の項目は入力が必須です</h6>
    </div>
  </div>

  <%= form_with model: @member, url: admin_member_path do |f| %>
      
    <div class="row justify-content-center">
			<div class ="col-sm-md-7">
			  <table class="table table-bordered">
			    <tr>
            <th class="table-active">ユーザーID</th>
            <td><%= @member.id %></td>
          </tr>
          <tr>
            <th class="table-active">プロフィール画像</th>
            <td><%= f.file_field :profile_image, accept: "image/*", :placeholder =>"#{@member.profile_image}" %></td>
          </tr>
          <tr>
            <th class="table-active"><span class="text_red">※</span>ユーザー名(50字以内)</th>
            <td><%= f.text_field :name, :placeholder =>"#{@member.name}" %></td>
          </tr>
          <tr>
            <th class="table-active"><span class="text_red">※</span>メールアドレス</th>
            <td><%= f.email_field :email, autofocus: true, autocomplete: "email", :placeholder =>"#{@member.email}" %></td>
          </tr>
          <tr>
            <th class="table-active">好きなワインのジャンル</th>
            <td>
              <%= f.select :favorite_genre, Member.favorite_genres.keys, {}, :placeholder =>"#{@member.favorite_genre}" %>
            </td>
          </tr>
          <tr>
            <th class="table-active">在住県</th>
            <td>
              <%= f.select :prefecture, Member.prefectures.keys, {}, :placeholder =>"#{@member.prefecture}" %>
            </td>
          </tr>
          <tr>
            <th class="table-active">紹介文</th>
            <td><%= f.text_area :introduction, :placeholder =>"#{@member.introduction}" %></td>
          </tr>
          <tr>
            <th class="table-active">会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, "false" %>
              <%= f.label :is_deleted_false, "有効" %>
              <%= f.radio_button :is_deleted, "true", class:"ml-4" %>
              <%= f.label :is_deleted_false, "退会" %>
            </td>
          </tr>
        </table>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class ="col-sm-md-7 text-center">
        <%= f.submit "Update", class:"btn btn-info px-5 py-1 member_edit__update_btn" %>
      </div>
    </div>
    <% end %>
    
</div>

app/views/admin/members/follower.html.erb
<%= render 'admin/members/index', title: @title, q: @q, members: @members, url: followers_admin_member_path(@member) %>

app/views/admin/members/followers.html.erb
<%= render 'admin/members/index', title: @title, q: @q, members: @members, url: followers_admin_member_path(@member) %>

app/views/admin/members/followings.html.erb
<%= render 'admin/members/index', title: @title, q: @q, members: @members, url: followings_admin_member_path(@member) %>

app/views/admin/members/followings_wine.html.erb
<div class='container my-4 wine_index_container'>

  <%= render 'admin/wines/member_info', member: @member %>

  <div class="row">
    <h5 class="col-sm-md text-center mx-auto text_blue">
      <i class="fas fa-users"></i>&nbsp;&nbsp;<%= @member.name %>がフォローしているユーザーのナチュール投稿🍷<!--<span> (<%#= @bookmark_wines.count %>件)</span> %> -->
    </h5>
  </div>

  <%#= render 'public/wines/index', wines: @bookmark_wines, member: @member, genres: @genres %>

    <!-- タブ作成-->
    <div class ="row justify-content-center mt-3" >
      <div class ="col">
        <ul id="tab-menu">
            <li><a href="#tab-All" class="active">All</a></li>
          <% @genres.each do |genre| %>
            <li><a href="#tab-<%= genre.genre_name %>" class=""><%= genre.genre_name %></a></li>
          <% end %>
          </ul>
       </div>
    </div>

    <!-- タブの内容作成-->
    <div class ="row">
      <div id="tab-contents">

        <!-- Allを表示-->
        <div id="tab-All" class="tab">
          <% @followings_wines.each do |wine| %>

            <div>
              <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
                <div class ="card">

                  <div class ="card_spot_name ml-2">
                    <%= link_to spot_path(wine.spot) do %>
                      📍<%= wine.spot.spot_name %>
                    <% end %>
                  </div>
                  <div class ="card_wine_image text-center">
                    <%= link_to wine_path(wine) do %>
                      <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                    <% end %>
                  </div>
                  <div class ="card_member_name ml-4 mt-1">
                   <%= link_to wines_myindex_path(wine.member.id) do %>
                      <%= wine.member.name %>
                    <% end %>
                  </div>
                  <div id= "wine_<%= wine.id %>">
                    <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                      <% if wine.is_again == true && wine.member == current_member %>
                        <div class ="card_against mr-4 pr-5">
                          <i class="fas fa-check"></i>
                        </div>
                      <% end %>
                      <div class ="card_comment ml-5">
                        <%= link_to wine_path(wine.id) do%>
                          <i class="far fa-comment"></i><%= wine.comments.count %>
                        <% end %>
                      </div>
                      <div class ="card_favorites favorite-btn mx-3">
                         <%= render 'public/favorites/favorite-btn', wine: wine %>
                      </div>
                      <div class ="card_bookmark bookmark-btn mr-3">
                         <%= render 'public/bookmarks/bookmark-btn', wine: wine %>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          <% end %>
        </div>

       <!-- ジャンルごとに表示-->
        <% @genres.each do |genre| %>
          <div id="tab-<%= genre.genre_name %>" class="tab">
            <%# フォローした人の投稿一覧 %>
            <% genre.wines.where(member_id: @member.followings.where(is_deleted: false)).each do |wine| %>

              <div>
                <div class="card-deck wine_card my-2 pt-1 px-1" style="width:310px;">
                  <div class ="card">

                    <div class ="card_spot_name ml-2">
                      <%= link_to spot_path(wine.spot) do %>
                       📍<%= wine.spot.spot_name %>
                      <% end %>
                    </div>
                    <div class ="card_wine_image text-center">
                      <%= link_to wine_path(wine) do %>
                        <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                      <% end %>
                    </div>
                    <div class ="card_member_name ml-4 mt-1">
                      <%= link_to wines_myindex_path(wine.member.id) do %>
                        <%= wine.member.name %>
                      <% end %>
                    </div>

                    <div id= "wine_<%= wine.id %>">
                      <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                        <% if wine.is_again == true && wine.member == current_member %>
                          <div class ="card_against mr-4 pr-5">
                            <i class="fas fa-check"></i>
                          </div>
                        <% end %>
                        <div class ="card_comment ml-5">
                        <%= link_to wine_path(wine.id) do%>
                          <i class="far fa-comment"></i><%= wine.comments.count %>
                        <% end %>
                      </div>
                      <div class ="card_favorites favorite-btn mx-3">
                         <%= render 'public/favorites/favorite-btn', wine: wine %>
                      </div>
                      <div class ="card_bookmark bookmark-btn mr-3">
                         <%= render 'public/bookmarks/bookmark-btn', wine: wine %>
                      </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/admin/members/index.html.erb
<%= render 'admin/members/index', title: @title, q: @q, members: @members, url: admin_members_path %>

app/views/admin/members/show.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="col-sm-md-6 text-left">
      <h2><%= @member.name %>さんの登録情報</h2>
    </div>
  </div>
  <div class="row justify-content-center mb-3">
    <div class="col-sm-md-6 text-right">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-md-6">
      <table class="table table-bordered">
        <tr>
          <th class="table-active">ユーザーID</th>
          <td><%= @member.id %></td>
        </tr>
        <tr>
        <tr>
          <th class="table-active">プロフィール画像</th>
          <td>
            <%= image_tag @member.get_profile_image(150,150), class: "rounded-circle" %>
          </td>
        </tr>
        <tr>
          <th class="table-active">ユーザーネーム(※必須:50文字以内)</th>
          <td><%= @member.name %></td>
        </tr>
        <tr>
          <th class="table-active">メールアドレス(※必須)</th>
          <td><%= @member.email %></td>
        </tr>
        <tr>
          <th class="table-active">好きなワインのジャンル</th>
          <td><%= @member.favorite_genre %></td>
        </tr>
        <tr>
          <th class="table-active">在住県</th>
          <td><%= @member.prefecture %></td>
        </tr>
        <tr>
          <th class="table-active">紹介文</th>
          <%# 改行が反映されるように記述 %>
          <td><%#= @member.introduction %><%=safe_join(@member.introduction.split("\n"),tag(:br))%></td>
        </tr>
        <tr>
          <th class="table-active">ステータス</th>
          <td>
            <% if @member.is_deleted == false %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-secondary">退会</div>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
    <div class="row justify-content-center">
      <div class="col-sm-md-5 text-right ml-5">
        <% if @member.name != "guestuser" %>
          <%= link_to "→ Edit", edit_admin_member_path(@member), class:"btn btn-info btn-info px-5 py-1 member_show__edit_btn" %>
        <% end %>
      </div>
    </div>
</div>