config/routes.rb
Rails.application.routes.draw do
  # root to: 'homes#top'
  # get "/about" => "homes#about"

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    # get 'top' => 'homes#top', as: 'top'
    root "homes#top"
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :members, only: [:index, :show, :edit, :update] do
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :wines, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "spots/spots_list" => "spots#spots_list"
    resources :spots, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "members/unsubscribe" => "members#unsubscribe", as: "confirm_unsubscribe"
    patch "members/withdraw" => "members#withdraw", as: "withdraw_members"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      # member doを使うと、ユーザーidが含まれてるurlを使えるようになる。
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :wines, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      # 1人のメンバーは1つの投稿に対して1回しかいいねできないためいいねのidはURLに含める必要がない(params[:id]を使わなくても良い)
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :spots, only: [:index, :show, :create, :new, :edit, :update]
  end

  # ゲストログイン用
  devise_scope :member do
    post "members/guest_sign_in", to: "members/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
  belongs_to :member
  belongs_to :genre
  belongs_to :spot
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :wine_image, presence: true

  has_one_attached :wine_image

  # 投稿写真を表示するためのメソッドを作成。画像サイズの変更。
  def get_wine_image(width, height)
    wine_image.variant(resize_to_limit: [width, height]).processed
  end

  # 引数で渡されたメンバーidがFavoritesテーブル内に存在（exists?） していればtrue、存在していなければfalseを返す
  # bookmark-btnファイルで使用
  def favorited_by?(member)
    favorites.exists?(member_id: member.id)
  end
  
  # favorite-btnファイルで使用
  def bookmarked_by?(member)
    bookmarks.exists?(member_id: member.id)
  end
end

app/controllers/admin/wines_controller.rb
class Admin::WinesController < ApplicationController
  def index
    @wines = Wine.includes(:member).where(member: { is_deleted: false }).order(id: "DESC")
    @genres = Genre.all
  end

  def myindex
    @member = Member.find(params[:id])
    @wines = @member.wines.order(id: "DESC")
    @genres = Genre.all
  end

  def again_index
    @member = Member.find(params[:id])
    @wines = @member.wines.all
    @again_wines = @wines.where(is_again: true).order(id: "DESC")
    @genres = Genre.all
  end
  
  def mymap
    @member = Member.find(params[:id])
    # spotテーブルとwineテーブルを結合して、wineの情報があるものだけ取ってきている
    # 結合すると、wineの個数分spotのレコードができてしまうので、uniqで重複削除をしている
    @spots = Spot.joins(:wines).where(wines: {member_id: @member}).all.uniq
  end


  def show
    @wine = Wine.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @wine = Wine.find(params[:id])
    @spot = @wine.spot
  end

  def update
    @wine = Wine.find(params[:id])
    if @wine.update(wine_params)
      flash[:notice] = "ナチュール投稿の更新が完了しました。"
      redirect_to admin_wine_path(@wine.id)
    else
      flash[:error] = "※情報が足りません"
      render :edit
    end
  end

  def destroy
    wine = Wine.find(params[:id])
    if wine.destroy
      flash[:notice] = "削除が完了しました。"
      redirect_to admin_wines_path
    else
      flash[:error] = "削除が完了できていません。"
      render :show
    end
  end

  private
    def wine_params
      params.require(:wine).permit(:member_id, :genre_id, :spot_id, :wine_name, :production_country, :production_year, :rate, :impression, :is_again, :wine_image)
    end

    def member_params
      params.require(:member).permit(:name, :profile_image, :favorite_genre, :prefecture, :introduction, :is_deleted)
    end

    def spot_params
      params.require(:spot).permit(:spot_name, :address, :telephone_number, :lat, :lng)
    end
end

app/helpers/admin/wines_helper.rb
module Admin::WinesHelper
end

app/views/admin/wines/_index.html.erb
<!-- タブ作成-->
<div class ="row justify-content-center mt-3" >
  <div class ="col">
    <ul id="tab-menu">
        <li><a href="#tab-All" class="active">All</a></li>
      <% genres.each do |genre| %>
        <li><a href="#tab-<%= genre.genre_name %>" class=""><%= genre.genre_name %></a></li>
      <% end %>
      </ul>
   </div>
</div>

<!-- タブの内容作成-->
<div class ="row">
  <div id="tab-contents">

    <!-- Allを表示-->
    <div id="tab-All" class="tab">
      <% wines.each do |wine| %>
       <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
        <div id="bookmark_list_<%= wine.id %>">
          <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
            <div class ="card">

              <div class ="card_spot_name ml-2">
                <%= link_to admin_spot_path(wine.spot) do %>
                  📍<%= wine.spot.spot_name %>
                <% end %>
              </div>
              <div class ="card_wine_image text-center">
                <%= link_to admin_wine_path(wine) do %>
                  <%= image_tag wine.get_wine_image(260,290) %>
                <% end %>
              </div>
              <div class ="card_member_name ml-4 mt-1">
               <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                  <%= wine.member.name %>
                <% end %>
              </div>
              <div id= "wine_<%= wine.id %>">
                <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                  <% if wine.is_again == true %>
                    <div class ="card_against mr-5 pr-5">
                      <i class="fas fa-check"></i>
                    </div>
                  <% end %>
                  <div class ="card_comment ml-5">
                    <%= link_to admin_wine_path(wine.id) do%>
                      <i class="far fa-comment"></i><%= wine.comments.count %>
                    <% end %>
                  </div>
                  <div class ="card_favorites favorite-btn mx-3">
                     ♡<%= wine.favorites.count %>
                  </div>
                </div>
              </div>

            </div>
          </div>
        </div>
      <% end %>
    </div>

   <!-- ジャンルごとに表示-->
    <% genres.each do |genre| %>
      <div id="tab-<%= genre.genre_name %>" class="tab">
        <%# genre.wines.where(member_id: member.id).each do |wine| %>
        <%# genre.wines.where(member_id: member.id, is_again: true).each do |wine| %>
        <%# genre.wines.where(spot_id: spot.id).each do |wine| %>
        <% genre.wines.each do |wine| %>
          <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
          <div id="bookmark_list_<%= wine.id %>">
            <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
              <div class ="card">

                <div class ="card_spot_name ml-2">
                  <%= link_to admin_spot_path(wine.spot) do %>
                   📍<%= wine.spot.spot_name %>
                  <% end %>
                </div>
                <div class ="card_wine_image text-center">
                  <%= link_to admin_wine_path(wine) do %>
                    <%= image_tag wine.get_wine_image(260,290) %>
                  <% end %>
                </div>
                <div class ="card_member_name ml-4 mt-1">
                  <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                    <%= wine.member.name %>
                  <% end %>
                </div>

                <div id= "wine_<%= wine.id %>">
                  <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                    <% if wine.is_again == true %>
                    <div class ="card_against mr-5 pr-5">
                      <i class="fas fa-check"></i>
                    </div>
                  <% end %>
                    <div class ="card_comment ml-5">
                      <%= link_to admin_wine_path(wine.id) do%>
                        <i class="far fa-comment"></i><%= wine.comments.count %>
                      <% end %>
                    </div>
                    <div class ="card_favorites favorite-btn mx-3">
                      ♡<%= wine.favorites.count %>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
</div>

    <script>
    //初期設定で表示されるのはtab-Allのコンテンツだけにして、それ以外の内容は非表示にする
      $('#tab-contents .tab[id != "tab-All"]').hide();

　　//id="tab-menu"のaタグがクリックされたときに、処理を実行
      $('#tab-menu a').on('click', function(event) {
        //id="tab-contents"内のいずれかのタブがクリックされたときに、そのタブ内の全コンテンツをいったん非表示
        $("#tab-contents .tab").hide();
        //activeクラスを削除する(CSSを対応させるため)
        $("#tab-menu .active").removeClass("active");
        //$(this)のとき(タブがクリックされたとき)activeクラスを追加する
        $(this).addClass("active");
        //href属性を取得し、取得したhref属性の中身を表示
        $($(this).attr("href")).show();
        event.preventDefault();
      });
   </script>


    <script src="javascript/src/jquery.min.js"></script>

app/views/admin/wines/_member_info.html.erb
  <div class='row mb-5 member_info_profile'>
    <div class="col-sm-3 member_info_top">
        <h4 class="text-left">
          <%= image_tag member.get_profile_image(70,70), class: "rounded-circle member_info_profile_image" %>
          <%= member.name %>
          <%= link_to admin_member_path(member), class: "text_blue" do %>
            &nbsp;<i class="fas fa-user-cog"></i>
          <% end %>
        </h4>
        <h6 class="mt-3 text-center">
        <%= link_to followings_admin_member_path(member), class: "text_blue" do %>
          フォロー数　：<%= member.followings.where(is_deleted: false).count %>
        <% end %></br>
        <%= link_to followers_admin_member_path(member), class: "text_blue" do %>
          フォロワー数：<%= member.followers.where(is_deleted: false).count %>
        <% end %>
        </h6>
    </div>

    <div class="col-sm-md-4 myindex_show_table">
      <table class="table table-sm" style="color: #555555;">
        <tr>
          <th class="text-left">在住県</th>
          <td class="text-left"><%= member.prefecture %></td>
        </tr>
        <tr>
          <th class="text-left">好きなワインのジャンル</th>
          <td class="text-left"><%= member.favorite_genre %></td>
        </tr>
        <tr>
          <th class="text-left">紹介文</th>
          <td class="text-left">
            <%# 改行をviewページに反映させる %>
            <%#= member.introduction %><%=safe_join(member.introduction.split("\n"),tag(:br))%>
          </td>
        </tr>
      </table>
    </div>

    <div class="col-sm-3">
      <div class="btn">
        <%= link_to admin_wines_mymap_path(member), class: "member_info_content_list" do %>
          <h7><i class="fas fa-map-marked-alt"></i>&nbsp;ナチュールMap</h7>
        <% end %>
      </div>
      <div class="btn">
        <%= link_to admin_wines_myindex_path(member), class: "member_info_content_list" do %>
          <h7><i class="fas fa-wine-bottle"></i>ナチュール記録all</h7>
        <% end %>
      </div>
      <div class="btn">
        <%= link_to admin_wines_again_index_path(member), class: "member_info_content_list" do %>
          <i class="fas fa-check"></i>また飲みたいナチュール
        <% end %>
      </div>
      <div class="btn">
        <%=link_to bookmarks_admin_member_path(member), class: "member_info_content_list" do %>
          <i class="fas fa-bookmark"></i>ブックマークした投稿
        <% end %>
      </div>
      <div class="btn">
        <%=link_to followings_wine_admin_member_path(member), class: "member_info_content_list" do %>
          <i class="fas fa-users"></i>&nbsp;フォローユーザーの投稿
        <% end %>
      </div>
    </div>

    <div class="col-sm-md-2">
    </div>

  </div>

app/views/admin/wines/again_index.html.erb
<div class='container my-4 wine_index_container'>
  
  <%= render 'admin/wines/member_info', member: @member %>
  
  <div class="row">
    <h5 class="col-sm-md text-center mx-auto text_blue">
      <%= @member.name %>のまた飲みたいナチュール🍷<span> (<%= @again_wines.count %>件)</span>
    </h5>
  </div>

  <%#= render 'admin/wines/index', wines: @again_wines, member: @member, genres: @genres %>
  
    <!-- タブ作成-->
  <div class ="row justify-content-center mt-3" >
    <div class ="col">
      <ul id="tab-menu">
          <li><a href="#tab-All" class="active">All</a></li>
        <% @genres.each do |genre| %>
          <li><a href="#tab-<%= genre.genre_name %>" class=""><%= genre.genre_name %></a></li>
        <% end %>
        </ul>
     </div>
  </div>
  
  <!-- タブの内容作成-->
  <div class ="row">
    <div id="tab-contents">
  
      <!-- Allを表示-->
      <div id="tab-All" class="tab">
        <% @again_wines.each do |wine| %>
         <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
          <div id="bookmark_list_<%= wine.id %>">
            <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
              <div class ="card">
  
                <div class ="card_spot_name ml-2">
                  <%= link_to admin_spot_path(wine.spot) do %>
                    📍<%= wine.spot.spot_name %>
                  <% end %>
                </div>
                <div class ="card_wine_image text-center">
                  <%= link_to admin_wine_path(wine) do %>
                    <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                  <% end %>
                </div>
                <div class ="card_member_name ml-4 mt-1">
                 <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                    <%= wine.member.name %>
                  <% end %>
                </div>
                <div id= "wine_<%= wine.id %>">
                  <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                    <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                    <div class ="card_comment ml-5">
                      <%= link_to admin_wine_path(wine.id) do%>
                        <i class="far fa-comment"></i><%= wine.comments.count %>
                      <% end %>
                    </div>
                    <div class ="card_favorites favorite-btn mx-3">
                       ♡<%= wine.favorites.count %>
                    </div>
                  </div>
                </div>
  
              </div>
            </div>
          </div>
        <% end %>
      </div>
  
     <!-- ジャンルごとに表示-->
      <% @genres.each do |genre| %>
        <div id="tab-<%= genre.genre_name %>" class="tab">
          <% genre.wines.where(member_id: @member.id, is_again: true).each do |wine| %>
            <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
            <div id="bookmark_list_<%= wine.id %>">
              <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
                <div class ="card">
  
                  <div class ="card_spot_name ml-2">
                    <%= link_to admin_spot_path(wine.spot) do %>
                     📍<%= wine.spot.spot_name %>
                    <% end %>
                  </div>
                  <div class ="card_wine_image text-center">
                    <%= link_to admin_wine_path(wine) do %>
                      <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                    <% end %>
                  </div>
                  <div class ="card_member_name ml-4 mt-1">
                    <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                      <%= wine.member.name %>
                    <% end %>
                  </div>
  
                  <div id= "wine_<%= wine.id %>">
                    <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                      <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                      <div class ="card_comment ml-5">
                        <%= link_to admin_wine_path(wine.id) do%>
                          <i class="far fa-comment"></i><%= wine.comments.count %>
                        <% end %>
                      </div>
                      <div class ="card_favorites favorite-btn mx-3">
                        ♡<%= wine.favorites.count %>
                      </div>
                    </div>
                  </div>
  
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  
    </div>
  </div>

</div>

app/views/admin/wines/edit.html.erb
<div class="container my-3">
  <div class="row-sm-md">
    <div class="col-sm-md">
      <h2>ナチュール投稿編集</h2>
    </div>
  </div>
  <div class="row-sm-md mt-3">
    <div class="col-sm-md-7">
      <h6 class="text_red">※の項目は入力が必須です</h6>
    </div>
  </div>
  
  <%= render 'admin/wines/wine_form', wine: @wine, spot: @spot, method: admin_wine_path(@wine) %>

</div>

app/views/admin/wines/index.html.erb
<div class='container my-4 wine_index_container'>
  <div class='row'>
    <div class='col-sm-md text-center mx-auto text_blue'>
      <h4>みんなのナチュール記録🍷<span class="h5"> (<%= @wines.count %>件)</span></h4>
    </div>
  </div>

   <%#= render 'admin/wines/index', wines: @wines, genres: @genres %>
   
   <!-- タブ作成-->
<div class ="row justify-content-center mt-3" >
  <div class ="col">
    <ul id="tab-menu">
        <li><a href="#tab-All" class="active">All</a></li>
      <% @genres.each do |genre| %>
        <li><a href="#tab-<%= genre.genre_name %>" class=""><%= genre.genre_name %></a></li>
      <% end %>
      </ul>
   </div>
</div>

  <!-- タブの内容作成-->
  <div class ="row">
    <div id="tab-contents">
  
      <!-- Allを表示-->
      <div id="tab-All" class="tab">
        <% @wines.each do |wine| %>
         <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
          <div id="bookmark_list_<%= wine.id %>">
            <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
              <div class ="card">
  
                <div class ="card_spot_name ml-2">
                  <%= link_to admin_spot_path(wine.spot) do %>
                    📍<%= wine.spot.spot_name %>
                  <% end %>
                </div>
                <div class ="card_wine_image text-center">
                  <%= link_to admin_wine_path(wine) do %>
                    <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                  <% end %>
                </div>
                <div class ="card_member_name ml-4 mt-1">
                 <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                    <%= wine.member.name %>
                  <% end %>
                </div>
                <div id= "wine_<%= wine.id %>">
                  <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                    <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                    <div class ="card_comment ml-5">
                      <%= link_to admin_wine_path(wine.id) do%>
                        <i class="far fa-comment"></i><%= wine.comments.count %>
                      <% end %>
                    </div>
                    <div class ="card_favorites favorite-btn mx-3">
                       ♡<%= wine.favorites.count %>
                    </div>
                  </div>
                </div>
  
              </div>
            </div>
          </div>
        <% end %>
      </div>
  
     <!-- ジャンルごとに表示-->
      <% @genres.each do |genre| %>
        <div id="tab-<%= genre.genre_name %>" class="tab">
          <% genre.wines.each do |wine| %>
            <!--ブックマークをdestroyした際に一覧から消す非同期設定のためにidを設定-->
            <div id="bookmark_list_<%= wine.id %>">
              <div class="card-deck wine_card my-2 pt-1 px-1 text_blue" style="width:310px;">
                <div class ="card">
  
                  <div class ="card_spot_name ml-2">
                    <%= link_to admin_spot_path(wine.spot) do %>
                     📍<%= wine.spot.spot_name %>
                    <% end %>
                  </div>
                  <div class ="card_wine_image text-center">
                    <%= link_to admin_wine_path(wine) do %>
                      <%= image_tag wine.get_wine_image(260,290), :alt => "wine画像", class:"index_wine_img" %>
                    <% end %>
                  </div>
                  <div class ="card_member_name ml-4 mt-1">
                    <%= link_to admin_wines_myindex_path(wine.member.id) do %>
                      <%= wine.member.name %>
                    <% end %>
                  </div>
  
                  <div id= "wine_<%= wine.id %>">
                    <div class ="row card_under_info d-flex justify-content-end mx-1 mt-1">
                      <% if wine.is_again == true %>
                      <div class ="card_against mr-5 pr-5">
                        <i class="fas fa-check"></i>
                      </div>
                    <% end %>
                      <div class ="card_comment ml-5">
                        <%= link_to admin_wine_path(wine.id) do%>
                          <i class="far fa-comment"></i><%= wine.comments.count %>
                        <% end %>
                      </div>
                      <div class ="card_favorites favorite-btn mx-3">
                        ♡<%= wine.favorites.count %>
                      </div>
                    </div>
                  </div>
  
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  
    </div>
  </div>

</div>

app/views/admin/wines/show.html.erb
<div class="container justify-content-center wine_show_main my-4">
  <div class="row mt-5 justify-content-center">
    <div class="wine_show_contents">
        <div class="col-sm-md wine_show_content">
          <%= link_to admin_spot_path(@wine.spot) do %>
            📍<%= @wine.spot.spot_name %></br>
          <% end %>
           <%= image_tag @wine.get_wine_image(400,400), class: "wine_show_image" %></br>

           <div id= "wine_<%= @wine.id %>">
             <h4 class="wine_show__under_info d-flex justify-content-end mt-3 mr-3">
               <% if @wine.is_again == true %>
                <div class ="against mr-5 pr-5">
                  <i class="fas fa-check"></i>
                </div>
               <% end %>
               <div class="comments_count ml-1">
                 <%= render "admin/comments/counter", wine: @wine %>
               </div>
               <div class= "favorite-btn mx-4">
                 ♡<%= @wine.favorites.count %>
               </div>
             </h4>
           </div>
        </div>

        <div class="col-sm-md mt-3">
          <table class="table wine_show_table">
            <tr>
              <th><%= image_tag @wine.member.get_profile_image(50,50), class: "rounded-circle" %></th>
              <td>
                <%= link_to admin_wines_myindex_path(@wine.member.id) do %>
                  <%= @wine.member.name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>投稿日</th>
              <td><%= @wine.created_at.strftime('%Y/%m/%d') %> </td>
            </tr>
            <tr>
              <th>商品名</th>
              <td><%= @wine.wine_name%> </td>
            </tr>
            <tr>
              <th>生産国</th>
              <td><%= @wine.production_country %> </td>
            </tr>
            <tr>
              <th>年代</th>
              <td><%= @wine.production_year %> </td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @wine.genre.genre_name %> </td>
            </tr>
            <tr>
              <th>評価</th>
              <td><%= render "public/wines/static_rate", wine: @wine %></td>
            </tr>
            <tr>
              <th>感想</th>
              <td><%#= @wine.impression %><%=safe_join(@wine.impression.split("\n"),tag(:br))%></td>
            </tr>
            <tr>
              <th></th>
              <% if @wine.is_again == true %>
                <td class="is_again_text"><i class="fas fa-check"></i>また飲みたい</td>
              <% end %>
            </tr>
          </table>
          <div class="wine_show__edit_destroy_btn text-right">
              <%= link_to "Edit", edit_admin_wine_path(@wine), class: "wine_show__edit_btn px-2" %>
              <%= link_to "Delete", admin_wine_path(@wine), method: :delete, class: "wine_show__destroy_btn px-2", "data-confirm" => "本当に削除しますか？" %>
        　</div>
        </div>
      </div>
      <div class="wine_show_map justify-content-center text-center p-4 ml-3">
        <h3>Where is...?</h3>
        <div class="wine_show_map_info mb-2 mt-5">
          <%= link_to admin_spot_path(@wine.spot) do %>
            📍<%= @wine.spot.spot_name %></br>
          <% end %>
          〒<%= @wine.spot.address %>
          </div>
        <div id='map'></div>
      </div>
    </div>
  <div class="row justify-content-left mt-3">
    <div class="col-sm-md ml-5">
      <div class="comment ml-5">
        <%= render "admin/comments/comment", wine: @wine %>
      </div>
    </div>

  </div>
</div>

<style>
#map {
  height: 300px;
  width: 300px;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @wine.spot.lat %>, lng: <%= @wine.spot.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @wine.spot.lat %>, lng: <%= @wine.spot.lng %>},
    map: map
  });
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY']%>&callback=initMap" async defer></script>