config/routes.rb
Rails.application.routes.draw do
  # root to: 'homes#top'
  # get "/about" => "homes#about"

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    # get 'top' => 'homes#top', as: 'top'
    root "homes#top"
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :members, only: [:index, :show, :edit, :update] do
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    resources :genres, only: [:index, :edit, :create, :update, :destroy]
    resources :wines, only: [:index, :show, :edit, :update, :destroy] do
      resources :comments, only: [:destroy]
    end
    get "spots/spots_list" => "spots#spots_list"
    resources :spots, only: [:index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root "homes#top"
    get "/about" => "homes#about"
    get "members/unsubscribe" => "members#unsubscribe", as: "confirm_unsubscribe"
    patch "members/withdraw" => "members#withdraw", as: "withdraw_members"
    resources :members, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      # member doを使うと、ユーザーidが含まれてるurlを使えるようになる。
      member do
        get :bookmarks, :followings, :followers, :followings_wine
      end
    end
    get "wines/myindex/:id" => "wines#myindex", as: "wines_myindex"
    get "wines/again_index/:id" => "wines#again_index", as: "wines_again_index"
    get "wines/mymap/:id" => "wines#mymap", as: "wines_mymap"
    resources :wines, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
      # 1人のメンバーは1つの投稿に対して1回しかいいねできないためいいねのidはURLに含める必要がない(params[:id]を使わなくても良い)
      resource :favorites, only: [:create, :destroy]
      resource :bookmarks, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :spots, only: [:index, :show, :create, :new, :edit, :update]
  end

  # ゲストログイン用
  devise_scope :member do
    post "members/guest_sign_in", to: "members/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="devise-alert" style="background-color:#F8D7DA; padding:3px; width:100%; margin-bottom:10px; padding-top:10px;">
    <ul style="list-style: none;">
      <% resource.errors.full_messages.each do |message| %>
        <li style="color:rgb(114, 31, 31)"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="d-flex flex-column">
  <div class="container-fluid">

    <%#.レスポンシブ対応 画面サイズ 1025px以上から適用 %>
    <nav class="navbar navbar lg_size">
      <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin">
          <%= image_tag "logo.png", size: "120x90" %>
        </a>
      <% else %>
        <a class="navbar-brand" href="/">
          <%= image_tag "logo.png", size: "120x90" %>
        </a>
      <% end %>

      <div>
        <ul class="navbar-nav list-group list-group-horizontal" >
          <% if admin_signed_in? %>
            <!--管理者ログイン後-->
            <li class="nav-item mr-5">
                <h5 class="text_blue text_bold text_underline">~管理者でlogin中~</h5>
            </li>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", admin_members_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", admin_wines_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", admin_spots_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Spot登録一覧",admin_spots_spots_list_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link btn pr-1 pl-1 ml-4 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link btn pr-2 pl-2 ml-4 header-link' %>
            </li>
          <% elsif member_signed_in? %>
            <!--会員ログイン後-->
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Mypage", wines_myindex_path(current_member), class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ユーザー一覧", members_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", wines_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", spots_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-link btn pr-1 pl-1 ml-4 header-link' %>
            </li>
          <% else %>
            <!--ログイン前-->
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link btn pr-4 pl-4 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ユーザー一覧", members_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", wines_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", spots_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_member_session_path, class: 'nav-link btn pr-3 pl-3 ml-4 header-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>


    <%#.レスポンシブ対応 画面サイズ 1024px以下から適用 %>
    <nav class="navbar navbar md_size">
      <% if admin_signed_in? %>
        <a class="navbar-brand" href="/admin">
          <%= image_tag "logo.png", size: "120x90" %>
        </a>
      <% else %>
        <a class="navbar-brand" href="/">
          <%= image_tag "logo.png", size: "120x90" %>
        </a>
      <% end %>

      <div id="sp-menu" class="pt-3 justify-content-center nav-item">
        <ul class="navbar-nav text-center">
          <!--管理者ログイン後-->
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", admin_members_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", admin_wines_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", admin_spots_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Spot登録一覧",admin_spots_spots_list_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link btn mx-5 header-link' %>
            </li>
          <!--会員ログイン後-->
          <% elsif member_signed_in? %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Mypage", wines_myindex_path(current_member), class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ユーザー一覧", members_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", wines_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", spots_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ナチュール投稿", new_spot_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ログアウト", destroy_member_session_path, method: :delete, class: 'nav-link btn mx-5 header-link' %>
            </li>
          <!--ログイン前-->
          <% else %>
            <li class="nav-item">
              <%= link_to "About", about_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "ユーザー一覧", members_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "投稿一覧", wines_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item ">
              <%= link_to "Map", spots_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_member_session_path, class: 'nav-link btn mx-5 header-link' %>
            </li>
          <% end %>
        </ul>
      </div>

      <%# ハンバーガーアイコン %>
      <div id="hm-icon">
        <a class="menu-trigger nav-item" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>NaturNote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body style='background-color:#f7f6ed'>

    <div class="naturnote_container">
      <div class = "header" style="background-color:#f7f6ed">
        <%= render 'layouts/header' %>
      </div>

      <main>
        <div class="naturnote_main">
          <div class="flash-message">
            <%#　緑　%>
            <%= flash_message(flash[:success], :success) if flash[:success] %>
            <%#　赤　%>
            <%= flash_message(flash[:error], :danger) if flash[:error] %>
            <%#　黄　%>
            <%= flash_message(flash[:alert], :danger) if flash[:alert] %>
            <%#　青　%>
            <%= flash_message(flash[:notice], :info) if flash[:notice] %>
          </div>
          <%= yield %>
        </div>

      </main>

      <div class="footer-space"></div>

    <%#
    <footer>
      <div class="d-flex justify-content-center my-3">
      2023 NatureNote
      </div>
    </footer>
    %>

    </div>
  </body>
</html>